name: Update Translation Files ðŸŒ

on:
  pull_request:
    branches: [dev]
    paths:
      - "**.php"
      - "**.js"
      - "languages/*.po"
  workflow_dispatch:

jobs:
  update-translation-files:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get pull request labels
        id: get_pr_labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.pull_request.number }}
            });
            const labels = pr.data.labels.map(label => label.name).join(',');
            console.log('Pull request labels:', labels);
            core.setOutput('labels', labels);
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_GITHUB_ACTIONS }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: wp-cli/wp-cli-bundle

      # Update .pot file if PHP or JS files changed
      - name: Update POT file
        if: contains(github.event.pull_request.changed_files, '.php') || contains(github.event.pull_request.changed_files, '.js')
        run: |
          wp i18n make-pot . languages/${{ github.event.repository.name }}.pot \
            --domain="pressbooks-network-catalog" \
            --slug="pressbooks-network-catalog" \
            --package-name="Pressbooks Network Catalog" \
            --headers='{"Report-Msgid-Bugs-To": "https://github.com/pressbooks/pressbooks-network-catalog/issues"}'

      # Update .mo files if .po files changed
      - name: Generate .mo files
        if: contains(github.event.pull_request.changed_files, '.po')
        run: wp i18n make-mo languages

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push translation files
        run: |
          git checkout -b l10n/update-translations
          git add languages/
          git commit -m "chore(l10n): update translation files"
          git push origin l10n/update-translations
          gh pr create --title "Update translation files" --body "Automated update of translation files" --base ${{ github.head_ref }} --head l10n/update-translations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}